/*

This tool generates a C/C++ header file containing word sizes for given
system. This tool has to be compiled and called as a part of build process.

Copyright (C) 2014 Sergey Kolevatov

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/

// $Id: word_size.c 466 2014-04-29 17:00:00Z serge $

#include <stdio.h>

void main()
{
    printf(
        "// generated by word_size.c\n\n"
        "#ifndef WORD_SIZE_H\n"
        "#define WORD_SIZE_H\n"
        "\n"
        "#define SIZEOF_CHAR            ( %d )\n"
        "#define SIZEOF_SHORT           ( %d )\n"
        "#define SIZEOF_INT             ( %d )\n"
        "#define SIZEOF_LONG            ( %d )\n"
        "#define SIZEOF_LONG_LONG       ( %d )\n"
        "#define SIZEOF_VOID_P          ( %d )\n"
        "#define SIZEOF_FLOAT           ( %d )\n"
        "#define SIZEOF_DOUBLE          ( %d )\n"
        "#define SIZEOF_LONG_DOUBLE     ( %d )\n"
        "\n"
        "#define SIZEOF_SIZE_T          ( %d )\n"
        "\n"
        "#endif // WORD_SIZE_H\n"
,
    sizeof( char ),
    sizeof( short ),
    sizeof( int ),
    sizeof( long ),
    sizeof( long long ),
    sizeof( void* ),
    sizeof( float ),
    sizeof( double ),
    sizeof( long double ),
    sizeof( size_t )
 );
}
